[package]
name = "solana-arb-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
yellowstone-grpc-client = "1.11"
yellowstone-grpc-proto = "1.11"
solana-sdk = "1.16"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
