services:
  - type: web
    name: solana-arbitrage-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: MEV_RELAY
        sync: false
      - key: SOLANA_RPC
        sync: false
      - key: PRIVATE_KEY
        sync: false
